### ISSUE TITLE
documentation output value

### ISSUE THREAD

**Issue by adokter** [adokter/suntools#14]
Documentation of the output value is not accurate for some functions, for example `crepuscule()`:

_The function returns the time of crepuscular light, either as a fraction of a day or as a POSIXct object, depending on the POSIXct.out parameter._

However, when POSIXct.out=TRUE, it returns a `data.frame` object with named columns `day_frac` and `time`. Needs to be checked for all four functions and documentation updated.

**Comment by iskandari** [comment]
updated in #9 f0444c2f448354c399cd0db0faa573d7a32011bb
