### ISSUE TITLE
Incorrect timezone

### ISSUE THREAD

**Issue by GFerraz97** [adokter/suntools#15]
Hi,

I have been using the sunriset function for some time, and I was hoping that the suntools package would have this issue solved, but it doesn't. When running the code, the sunrise and sunset timestamps are outputted in the timezone where the script is executed, and not according to the timezone of the locations provided for the code.

As an example, I'm from Portugal, and I'm working with GPS data from birds tagged in Spain. When executing the sunriset function, the outputted times have the minutes according to the location of the individual, but the hour is in accordance with the current time in Portugal. So, instead of outputting timestamps in GMT + 2 (during summer), it will output timestamps in GMT + 1 (Portuguese timezone in the summer) and need to manually add one hour to obtain the correct sunrise or sunset time.

Any advice on how to solve this?

Best, 
Gonçalo.

**Comment by adokter** [comment]
@GFerraz97 thanks for the bug report - just to confirm: was this issue already present in sunMaptools? We have only ported the existing code and made it compatible sf package and the deprecation of sp package.

Could you post here a minimum reproducible example that shows the issue, including the local time zone you are in? Thanks!

@iskandari assigning to you for now

**Comment by GFerraz97** [comment]
Yes, this issue was already present in maptools.

I have been working with data from Spain collected during the summer (GMT+2), while I'm from Portugal (GMT+1). All my georeferenced records were collected in GMT+0, and I have transformed them to local time.

I have been using the following code to obtain the sunrise and sunset times. 

x2$sunrise_test <- sunriset(
  as.matrix(data.frame(x2$Longitude, x2$Latitude)),
  as.POSIXct(x2$local_time, format = "%Y-%m-%d %H:%M:%S"),
  direction = "sunrise",
  POSIXct.out = TRUE
)
x2$sunset_test <- sunriset(
  as.matrix(data.frame(x2$X_4326, x2$
[Example_data_sunriset.csv](https://github.com/adokter/suntools/files/14929684/Example_data_sunriset.csv)
Y_4326)),
  as.POSIXct(x2$local_time, format = "%Y-%m-%d %H:%M:%S"),
  direction = "sunset",
  POSIXct.out = TRUE
)

However, the output is provided in the timezone of my IP address. For instance, if I'm working in Portugal, the sunrise time for a location in Spain will be provided at the right minute but with an hour less due to the differences between time zones. The same issue occurs if I'm working in Spain and looking for data in Portugal. The sunrise time will be provided with an additional hour as my IP address is in a region with a different time zone.

I have also tried including the "tz" argument in the as.POSIXct function, but it did not make a difference.

I'm including a CSV file with an example of the data I have been working on. If you try to run the suntools with this file, you will notice that the sunrise time is displayed in your timezone, rather than the correct one (which should be GMT+1 in this specific file).
[Example_data_sunriset.csv](https://github.com/adokter/suntools/files/14929645/Example_data_sunriset.csv)

**Comment by GFerraz97** [comment]
In my last comment I have sent the wrong file. Here's the correct one. 
[Example_data_sunriset.csv](https://github.com/adokter/suntools/files/14929749/Example_data_sunriset.csv)

**Comment by adokter** [comment]
```
library(readr)
library(suntools)

x2 <- read_delim("~/Downloads/Example_data_sunriset.csv", delim=";")

x2$sunrise_test <- sunriset(
  as.matrix(data.frame(x2$Longitude, x2$Latitude)),
  as.POSIXct(x2$local_time, format = "%Y-%m-%d %H:%M:%S"),
  direction = "sunrise",
  POSIXct.out = TRUE
)
x2$sunset_test <- sunriset(
  as.matrix(data.frame(x2$Longitude, x2$Latitude)),
  as.POSIXct(x2$local_time, format = "%Y-%m-%d %H:%M:%S"),
  direction = "sunset",
  POSIXct.out = TRUE
)

data.frame(lat=x2$Latitude, lon=x2$Longitude, time=x2$local_time, sunrise=x2$sunrise_test$time, sunset=x2$sunset_test$time)
```
Produces:
```
       lat       lon                time             sunrise              sunset
1  37.61590 -7.567844 2022-05-31 01:58:01 2022-05-31 05:10:55 2022-05-31 19:45:21
```
Bot sunrise and sunset are one hour too late in UTC time zone.

**Comment by iskandari** [comment]
@GFerraz97 your local times are read in from the start as UTC by default

```r
x2 <- read_delim("~/Downloads/Example_data_sunriset.csv", delim=";")
head(x2$local_time)

[1] "2022-05-31 01:58:01 UTC" "2022-05-31 02:28:08 UTC" "2022-05-31 02:58:10 UTC" "2022-05-31 03:27:57 UTC"
[5] "2022-05-31 03:58:31 UTC" "2022-05-31 04:28:02 UTC"
```

Regardless of your location, the sunset time will be returned in the timezone that you specify

```r
#  Santana de Cambas, PT
sunriset(
     matrix(c(-7.57,  37.6), nrow = 1),
     as.POSIXct("2023-06-01 01:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "Europe/Lisbon"),
     direction='sunset',
     POSIXct.out=TRUE
 )
   day_frac                time
1 0.8651652 2023-06-01 20:45:50
 
 sunriset(
     matrix(c(-7.57,  37.6), nrow = 1),
     as.POSIXct("2023-06-01 01:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "Europe/Madrid"),
     direction='sunset',
     POSIXct.out=TRUE
 )
   day_frac                time
1 0.9068318 2023-06-01 21:45:50
 

#Puebla de Guzman, ES 
 sunriset(
     matrix(c(-7.25, 37.61), nrow = 1),
     as.POSIXct("2023-06-01 01:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "Europe/Madrid"),
     direction='sunset',
     POSIXct.out=TRUE
 )
   day_frac                time
1 0.9059621 2023-06-01 21:44:35
 
 sunriset(
     matrix(c(-7.25, 37.61), nrow = 1),
     as.POSIXct("2023-06-01 01:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "Europe/Lisbon"),
     direction='sunset',
     POSIXct.out=TRUE
 )
   day_frac                time
1 0.8642954 2023-06-01 20:44:35
